### ISSUE TITLE
Convergence Issue with MaST in PST-Transformer

### ISSUE THREAD

**Issue by LauSkygh** [JohnsonSign/MaST-Pre#2]
Hi, and thank you for your great work! I've encountered a problem while attempting to replicate the use of MaST in PST-Transformer, as mentioned in your paper. It seems that the network fails to converge. Could you kindly provide the pre-trained code for PST-Transformer? Thank you very much!

**Comment by hduroy** [comment]
Hi,thank you for your great work ! I've the same issue.Could you give me some advice? Thank you very much!

**Comment by JohnsonSign** [comment]
> Hi, and thank you for your great work! I've encountered a problem while attempting to replicate the use of MaST in PST-Transformer, as mentioned in your paper. It seems that the network fails to converge. Could you kindly provide the pre-trained code for PST-Transformer? Thank you very much!

Compared with the P4DTransformer, PST-Transformer has considerably enhanced the modeling capacity of point cloud videos. Too many pre-training epochs (followed by fine-tuning) may induce oscillation. You can attempt to reduce the number of epochs to 30 or 50. In addition, directly restoring the original point coordinates will introduce some noise, which may also cause oscillation. You can improve this framework by predicting occupancy.

**Comment by JohnsonSign** [comment]
> Hi,thank you for your great work ! I've the same issue.Could you give me some advice? Thank you very much!

Compared with the P4DTransformer, PST-Transformer has considerably enhanced the modeling capacity of point cloud videos. Too many pre-training epochs (followed by fine-tuning) may induce oscillation. You can attempt to reduce the number of epochs to 30 or 50.
